### ISSUE TITLE
What if I set `enable=false` in `evalscope/registry/config/cfg_single.yaml`?

### ISSUE THREAD

**Issue by zhimin-z** [modelscope/evalscope#106]
Like `reviews_gen` or `rating_gen`? What would happen?

**Comment by wangxingjun778** [comment]
The prediction stage will be skipped if enable=false for specific model like chatglm3-6b, in the same way that could be happened in `review` and `rating` stages. 

The desc of stages:
`answers_gen`: predictions and output answers
`reviews_gen`: to call the judge model like `gpt-4` to get review results
`rating_gen`: to compute ELO score

**Comment by Yunnglin** [comment]
Due to a lack of activity for an extended period, we will be closing this issue. If you have any questions, please feel free to reopen it. If EvalScope has been helpful to you, we would appreciate a STAR as a form of support. Thank you!
