### ISSUE TITLE
swift eval 执行报错： cannot import name 'ftp_head' from 'datasets.utils.file_utils'

### ISSUE THREAD

**Issue by jackqdldd** [modelscope/evalscope#129]
`swift eval    --eval_url xxx/v1/chat/completions    --eval_dataset no    --eval_is_chat_model true    --model_type Qwen2-72B-Instruct-AWQ     --custom_eval_config custom_config.json
`
 File "/data/anaconda3/envs/evalscope/lib/python3.10/site-packages/modelscope/msdatasets/__init__.py", line 2, in <module>
    from modelscope.msdatasets.ms_dataset import MsDataset
  File "/data/anaconda3/envs/evalscope/lib/python3.10/site-packages/modelscope/msdatasets/ms_dataset.py", line 24, in <module>
    from modelscope.msdatasets.utils.hf_datasets_util import load_dataset_with_ctx
  File "/data/anaconda3/envs/evalscope/lib/python3.10/site-packages/modelscope/msdatasets/utils/hf_datasets_util.py", line 63, in <module>
    from modelscope.msdatasets.utils.hf_file_utils import get_from_cache_ms
  File "/data/anaconda3/envs/evalscope/lib/python3.10/site-packages/modelscope/msdatasets/utils/hf_file_utils.py", line 18, in <module>
    from datasets.utils.file_utils import hash_url_to_filename, get_authentication_headers_for_url, ftp_head, fsspec_head, \
ImportError: cannot import name 'ftp_head' from 'datasets.utils.file_utils' (/data/anaconda3/envs/evalscope/lib/python3.10/site-packages/datasets/utils/file_utils.py)

Package                       Version
----------------------------- -----------
absl-py                       2.1.0
accelerate                    0.34.2
addict                        2.4.0
aiofiles                      23.2.1
aiohappyeyeballs              2.4.0
aiohttp                       3.10.5
aiosignal                     1.3.1
aliyun-python-sdk-core        2.15.2
aliyun-python-sdk-kms         2.16.5
annotated-types               0.7.0
antlr4-python3-runtime        4.9.3
anyio                         4.4.0
async-timeout                 4.0.3
attrdict                      2.0.1
attrs                         24.2.0
binpacking                    1.5.2
cachetools                    5.5.0
certifi                       2024.8.30
cffi                          1.17.1
charset-normalizer            3.3.2
click                         8.1.7
colorama                      0.4.6
contourpy                     1.3.0
cpm-kernels                   1.0.11
crcmod                        1.7
cryptography                  43.0.1
cycler                        0.12.1
dacite                        1.8.1
datasets                      3.0.0
decord                        0.6.0
dill                          0.3.8
distro                        1.9.0
docstring_parser              0.16
editdistance                  0.8.1
einops                        0.8.0
et-xmlfile                    1.1.0
evalscope                     0.5.3
evaluate                      0.4.3
exceptiongroup                1.2.2
fastapi                       0.114.1
ffmpy                         0.4.0
filelock                      3.16.0
fonttools                     4.53.1
frozenlist                    1.4.1
fsspec                        2024.6.1
func_timeout                  4.3.5
future                        1.0.0
fuzzywuzzy                    0.18.0
gradio                        4.44.0
gradio_client                 1.3.0
grpcio                        1.66.1
h11                           0.14.0
h5py                          3.11.0
httpcore                      1.0.5
httpx                         0.27.2
huggingface-hub               0.24.7
idna                          3.8
immutabledict                 4.2.0
importlib_metadata            8.5.0
importlib_resources           6.4.5
jieba                         0.42.1
Jinja2                        3.1.4
jiter                         0.5.0
jmespath                      0.10.0
joblib                        1.4.2
json5                         0.9.25
jsonlines                     4.0.0
kiwisolver                    1.4.7
Levenshtein                   0.25.1
lxml                          5.3.0
Markdown                      3.7
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
matplotlib                    3.9.2
mdurl                         0.1.2
mmengine-lite                 0.10.4
modelscope                    1.18.0
mpmath                        1.3.0
ms-opencompass                0.1.0
ms-swift                      2.4.1
ms-vlmeval                    0.0.7
multidict                     6.1.0
multiprocess                  0.70.16
networkx                      3.3
nltk                          3.9.1
numpy                         1.26.4
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu12             9.1.0.70
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu12              2.20.5
nvidia-nvjitlink-cu12         12.6.68
nvidia-nvtx-cu12              12.1.105
omegaconf                     2.3.0
openai                        1.45.0
OpenCC                        1.1.9
openpyxl                      3.1.5
orjson                        3.10.7
oss2                          2.19.0
packaging                     24.1
pandas                        2.2.2
peft                          0.12.0
pillow                        10.4.0
pip                           24.2
platformdirs                  4.3.2
plotly                        5.24.1
ply                           3.11
portalocker                   2.10.1
prettytable                   3.11.0
protobuf                      5.28.1
psutil                        6.0.0
pyarrow                       17.0.0
pycparser                     2.22
pycryptodome                  3.20.0
pydantic                      2.9.1
pydantic_core                 2.23.3
pydub                         0.25.1
Pygments                      2.18.0
Pympler                       1.1
pyparsing                     3.1.4
pypinyin                      0.52.0
python-dateutil               2.9.0.post0
python-dotenv                 1.0.1
python-Levenshtein            0.25.1
python-multipart              0.0.9
pytz                          2024.2
PyYAML                        6.0.2
rank-bm25                     0.2.2
rapidfuzz                     3.9.7
regex                         2024.9.11
requests                      2.32.3
requests-toolbelt             1.0.0
rich                          13.8.1
rouge                         1.0.1
rouge-chinese                 1.0.3
rouge_score                   0.1.2
ruff                          0.6.4
sacrebleu                     2.4.3
safetensors                   0.4.5
scikit-learn                  1.5.2
scipy                         1.14.1
seaborn                       0.13.2
semantic-version              2.10.0
sentence-transformers         3.1.0
sentencepiece                 0.2.0
setuptools                    69.5.1
shellingham                   1.5.4
shtab                         1.7.1
simple-ddl-parser             1.6.1
simplejson                    3.19.3
six                           1.16.0
sniffio                       1.3.1
sortedcontainers              2.4.0
starlette                     0.38.5
sty                           1.0.6
sympy                         1.13.2
tabulate                      0.9.0
tenacity                      9.0.0
tensorboard                   2.17.1
tensorboard-data-server       0.7.2
termcolor                     2.4.0
threadpoolctl                 3.5.0
tiktoken                      0.7.0
timeout-decorator             0.5.0
tokenizers                    0.19.1
tomli                         2.0.1
tomlkit                       0.12.0
torch                         2.4.1
torchvision                   0.19.1
tqdm                          4.66.5
transformers                  4.42.4
transformers-stream-generator 0.0.5
triton                        3.0.0
trl                           0.10.1
typer                         0.12.5
typing_extensions             4.12.2
tyro                          0.8.10
tzdata                        2024.1
urllib3                       2.2.3
uvicorn                       0.30.6
validators                    0.34.0
wcwidth                       0.2.13
websockets                    12.0
Werkzeug                      3.0.4
wheel                         0.44.0
XlsxWriter                    3.2.0
xxhash                        3.5.0
yapf                          0.40.2
yarl                          1.11.1
zipp                          3.20.1

**Comment by Yunnglin** [comment]
请问完整的执行命令是什么 `--eval_url xxx/v1/chat/completions` 需要替换成部署的推理服务url，例如 `http://127.0.0.1:8000/v1/chat/completions`

**Comment by jackqdldd** [comment]
> 请问完整的执行命令是什么 `--eval_url xxx/v1/chat/completions` 需要替换成部署的推理服务url，例如 `http://127.0.0.1:8000/v1/chat/completions`

地址就是完整服务的地址，是不是版本不对？

**Comment by jackqdldd** [comment]
swift eval  --eval_url http://xxx-server-inter.xx.net.cn:52010/v1/chat/completions    --eval_dataset no    --eval_is_chat_model true    --model_type Qwen2-72B-Instruct-AWQ     --custom_eval_config custom_config.json

**Comment by Yunnglin** [comment]
请尝试使用datasets 2.21.0 版本
```shell
pip install datasets==2.21.0
```

**Comment by jackqdldd** [comment]
解决了，谢谢
