### ISSUE TITLE
swift eval 执行自定义数据集：dacite.exceptions.MissingValueError: missing value for field "data"

### ISSUE THREAD

**Issue by jackqdldd** [modelscope/evalscope#132]
swift eval  --eval_url http://xxx.net.cn:52010/v1/chat/completions    --eval_dataset no    --eval_is_chat_model true    --model_type Qwen2-72B-Instruct-AWQ     --custom_eval_config cumtomer_config.json

按照custom_dataset.md 准备的用例，执行的时候报错
![image](https://github.com/user-attachments/assets/dfe3dd3f-b3d7-4910-bbfa-209bc2e799e2)

**Comment by jackqdldd** [comment]
排查后发现是ms-swift项目的client_utils.py#get_model_list_client_async   接口404，
<img width="847" alt="image" src="https://github.com/user-attachments/assets/af99925c-fa03-44ef-8353-86632ba1e798">

api后面加/models   404了，这是为啥

**Comment by Yunnglin** [comment]
请问你的服务使用什么部署的，是否支持OpenAI API的格式

**Comment by jackqdldd** [comment]
解决了，swift eval --eval_url  地址传的不对，不能传完整的api地址，应该是地址到/v1就行了
错误：http://10.11.17.11:40105/v1/chat/completion
正确：http://10.11.17.11:40105/v1
