### ISSUE TITLE
使用自定义模板进行评测报错

### ISSUE THREAD

**Issue by mianbaoji** [modelscope/evalscope#139]
使用的是百炼提供的免费 CPU 环境
![image](https://github.com/user-attachments/assets/60484ac0-778e-4b10-8676-872b4994b590)
已经提前把模型文件下好了
调用代码
![image](https://github.com/user-attachments/assets/6824439f-5d2d-45be-8293-895d2ce08787)
使用 ms-swift/examples/pytorch/llm/eval_example/custom_config.json 报同样的错误
运行后报错
![image](https://github.com/user-attachments/assets/b505cee6-2501-4da2-ad73-4cdd2c99e359)
![image](https://github.com/user-attachments/assets/ed1782ec-4099-4e64-8437-3775cb526122)

环境信息：
![image](https://github.com/user-attachments/assets/2895485a-8968-481a-bd28-f14443b4a0e4)
![image](https://github.com/user-attachments/assets/b56cdd90-8ed8-452e-88c0-a79dcc6a8c38)

**Comment by Yunnglin** [comment]
看起来是环境中缺少了rouge_score这个包
请安装
```
pip install rouge_score
```

**Comment by wangxingjun778** [comment]
pip install rouge-score -U

**Comment by wangxingjun778** [comment]
main分支已更新requirements，强制要求rouge-score>=0.1.0

**Comment by wangxingjun778** [comment]
pip install rouge-score -U
