### ISSUE TITLE
测试结果指标数值相同

### ISSUE THREAD

**Issue by LHB-kk** [modelscope/evalscope#141]
测试时，为什么平均延迟和平均生成第一个token的时间是一样的？
![image](https://github.com/user-attachments/assets/d94ba458-3db3-4256-adde-86c5ef117416)

**Comment by LillyZhouXiHa** [comment]
同问，求问是什么原因

**Comment by lxline** [comment]
请问您是在非 Steam 模式下的压测吗？

在非 Stream 模式返回的情况下，客户端收到第一个 Token 的延迟 == 整个 Response 的延迟。因此计算结果是相等的。
