### ISSUE TITLE
访问api 服务，当并发数大于等于500时，出现请求失败

### ISSUE THREAD

**Issue by LHB-kk** [modelscope/evalscope#142]
![image](https://github.com/user-attachments/assets/66ca442c-ddbb-4a5e-b531-498a420a80b9)
当设置并发数大于等于500时，出现图片上的错误，请问是evalscope的原因嘛，还是api服务的原因？谢谢！

**Comment by wangxingjun778** [comment]
@lxline  帮忙看一下

**Comment by njzfw1024** [comment]
> ![image](https://private-user-images.githubusercontent.com/61236343/371836208-66ca442c-ddbb-4a5e-b531-498a420a80b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNTkyNTIsIm5iZiI6MTczMjI1ODk1MiwicGF0aCI6Ii82MTIzNjM0My8zNzE4MzYyMDgtNjZjYTQ0MmMtZGRiYi00YTVlLWI1MzEtNDk4YTQyMGE4MGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA3MDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYWRkMmYxZTRhN2Q1ODI4NTU4M2UwODc4ZGEzNGM0NDFmZTQ3Yjg1ZThmNDhmOWE4MTUzYTVmM2NlMTMwNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MdBOfgPNCGMeB1QSF2jC8y0Jxa2F53OkpsISNob7-xc) 当设置并发数大于等于500时，出现图片上的错误，请问是evalscope的原因嘛，还是api服务的原因？谢谢！

请问这是什么测试数据集

**Comment by Yunnglin** [comment]
> 由于长时间未收到活动，我们将关闭此问题。如果您有任何疑问，请随时重新打开它。如果EvalScope对您有所帮助，欢迎给我们点个STAR以示支持，谢谢！
