### ISSUE TITLE
模型性能测试报错

### ISSUE THREAD

**Issue by LHB-kk** [modelscope/evalscope#144]
evalscope perf --url 'xxxx:8000/v1/chat/completions' --parallel 150 --model '/models/Qwen2.5-7B-instruct/' \
    --log-every-n-query 400 --read-timeout=120 \
    --max-prompt-length 128000 --tokenizer-path "/models/Qwen2.5-7B-instruct/" \
    --api openai --query-template '{"model": "%m", "messages": [{"role": "user","content": "%p"}], "stream": false,"skip_special_tokens": false,"stop": ["<|im_end|>"]}'\
    --dataset openqa --dataset-path '/open_qa.jsonl' \
    --number 10000 \

运行上面命令时，出现以下报错：
![image](https://github.com/user-attachments/assets/b4e10866-0f91-4862-93c9-bd311c749ba7)

**Comment by wangxingjun778** [comment]
@lxline

**Comment by lxline** [comment]
您能不能提供一下环境信息（运行设备、版本等）？有助于我们复现该问题。
