### ISSUE TITLE
基础模型评测（qwen2-7b-chat）报错

### ISSUE THREAD

**Issue by ljh567** [modelscope/evalscope#147]
无法使用humaneval评测集是为什么
**脚本：**
ASCEND_RT_VISIBLE_DEVICES=0 \
swift eval \
    --model_type qwen-7b-chat \
    --eval_dataset humaneval \
    --infer_backend pt \
    --eval_backend Native \

**报错：**
2024-10-11 14:13:21,560 - evalscope - ERROR - No task found in tasks: ['arc', 'gsm8k', 'mmlu', 'cmmlu', 'ceval', 'bbh', 'general_qa'], got task_name: humaneval

**求解答，感谢！**

**Comment by Yunnglin** [comment]
swift中native backend目前不支持humaneval，建议使用opencompass backend，`--eval_backend OpenCompass`

**Comment by wangxingjun778** [comment]
补充，详细步骤可参考以下信息：

1. installation
```python
pip install ms-swift[eval]
pip install human-eval      # swift下个版本会集成进来，自动安装。
pip install vllm    # 如果安装则自动走vllm，如果不安装则会使用pt作为infer_backend
```

2. eval
`swift eval --model_type qwen2-7b-instruct --eval_dataset humaneval`
（--eval_backend 默认指向了OpenCompass）

3. 结果示例

dataset                                 version    metric            mode    qwen2-7b-instruct
--------------------------------------  ---------  ----------------  ------  --------- 考试 Exam --------- 
...
...
gsm8k                                   -          -                 -       -
TheoremQA                               -          -                 -       -
openai_humaneval                        8e312c     humaneval_pass@1  gen     75.00
