### ISSUE TITLE
使用OpenCompass Math数据集压测，可以使用few shot吗

### ISSUE THREAD

**Issue by tianshiyisi** [modelscope/evalscope#152]
通过OpenCompass Math数据集压测Qwen2.5-72B-Instruct，在zero shot下得分为49.18，远低于83.1，确认一下这里面的压测是不是使用了few-shot，evalscope是否可以支持
https://qwenlm.github.io/zh/blog/qwen2.5-llm/
![image](https://github.com/user-attachments/assets/aa9c3f59-514d-44b8-9174-220e6b268468)

**Comment by Yunnglin** [comment]
- 关于是否是few-shot，qwen github的eval部分没有找到MATH使用的配置，我也不太清楚
- OpenCompass提供的默认评测是zero-shot，若要使用few-shot，目前evalscope还不支持，但可以修改ms-opencompass库`opencompass/configs/datasets/math/math_gen.py` 来导入配置进行评测，修改为如下代码：
```python
from mmengine.config import read_base

with read_base():
    from .math_4shot_base_gen_43d5b6 import math_datasets
```
![image](https://github.com/user-attachments/assets/f1186194-d344-4bff-8603-a2ddde639132)

**Comment by tianshiyisi** [comment]
多谢，我试一下

**Comment by tianshiyisi** [comment]
@Yunnglin 多谢支持，问题已经解决：https://github.com/QwenLM/Qwen2.5/issues/1020
