### ISSUE TITLE
评估代码eval 运行如何不能本地加载数据集？

### ISSUE THREAD

**Issue by yawzhe** [modelscope/evalscope#154]
### dataset task: mmlu_test
 template: fewshot 
lang: en 
n_shot: 5
 ### output save_dir: saves/llama3-8b/lora/eval  
### eval batch_size: 4  上面的命令 发现得下载数据集，但是evalute下面有mmlu.zip数据集得压缩包，解压了，仍然还得下载，什么情况  ？参数 task_dir 直接设置得evalute路径发现似乎仍然得下载                                                                                                  
   download_mode  str  评估数据集的下载模式，默认值为 DownloadMode.REUSE_DATASET_IF_EXISTS。如果数据集已经存在则重复使用，否则则下载。 如何本地加载？

**Comment by Yunnglin** [comment]
请问评测时具体的运行命令是什么呢？
基本使用教程参考：https://evalscope.readthedocs.io/zh-cn/latest/get_started/basic_usage.html
