### ISSUE TITLE
C-MTEB上很多测评指标对不上，尤其是检索指标

### ISSUE THREAD

**Issue by xujunrt** [modelscope/evalscope#155]
用这个框架跑出来的指标不对，并且差异很大，尤其是检索数据集
CMTEB参考指标：https://github.com/FlagOpen/FlagEmbedding/tree/master/C_MTEB

**Comment by Yunnglin** [comment]
请提供一下您评测的模型和数据集，我们复现一下。本身框架接入的就是原始的CMTEB，不存在breaking change。

**Comment by xujunrt** [comment]
就是用的bge large zh

---- 回复的原邮件 ----
| 发件人 | Yunlin ***@***.***> |
| 发送日期 | 2024年10月16日 21:05 |
| 收件人 | modelscope/evalscope ***@***.***> |
| 抄送人 | xujunrt ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [modelscope/evalscope] C-MTEB上很多测评指标对不上，尤其是检索指标 (Issue #155) |

请提供一下您评测的模型和数据集，我们复现一下。本身框架接入的就是原始的CMTEB，不存在breaking change。

**Comment by xujunrt** [comment]
你们提供MTEB数据列表中检索数据，例如T2retrival

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月16日 21:05 |
| 收件人 | modelscope/evalscope ***@***.***> |
| 抄送人 | xujunrt ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [modelscope/evalscope] C-MTEB上很多测评指标对不上，尤其是检索指标 (Issue #155) |

能否提供一下具体是跑哪些任务 指标没有对齐？ 以及实际跑出来的结果可以选一部分列一下。

**Comment by Yunnglin** [comment]
使用的 pooling_mode是什么呢，是`cls`吗

**Comment by xujunrt** [comment]
对的，文本长度设置的为512 batchsize为512 prompt按照cmteb设置的

---- 回复的原邮件 ----
| 发件人 | Yunlin ***@***.***> |
| 发送日期 | 2024年10月16日 21:22 |
| 收件人 | modelscope/evalscope ***@***.***> |
| 抄送人 | xujunrt ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [modelscope/evalscope] C-MTEB上很多测评指标对不上，尤其是检索指标 (Issue #155) |

使用的 pooling_mode是什么呢，是cls吗

**Comment by Yunnglin** [comment]
ok我们验证一下

**Comment by xujunrt** [comment]
感谢，我明天把我具体的实验结果和配置也贴出来

---- 回复的原邮件 ----
| 发件人 | Yunlin ***@***.***> |
| 发送日期 | 2024年10月16日 21:32 |
| 收件人 | modelscope/evalscope ***@***.***> |
| 抄送人 | xujunrt ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [modelscope/evalscope] C-MTEB上很多测评指标对不上，尤其是检索指标 (Issue #155) |

ok我们验证一下

**Comment by xujunrt** [comment]
Ecoretrieval数据集评测最快，我这里跑出来的结果是59.4，cmteb评测结果为66

---- 回复的原邮件 ----
| 发件人 | Yunlin ***@***.***> |
| 发送日期 | 2024年10月16日 21:32 |
| 收件人 | modelscope/evalscope ***@***.***> |
| 抄送人 | xujunrt ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [modelscope/evalscope] C-MTEB上很多测评指标对不上，尤其是检索指标 (Issue #155) |

ok我们验证一下

**Comment by xujunrt** [comment]
![image](https://github.com/user-attachments/assets/03258a3a-03e6-435d-a200-a904e0ff25f2)

```
from evalscope.run import run_task
from evalscope.utils.logger import get_logger
import sys
logger = get_logger()


def run_eval(model_name_or_path,prompt,pooling_mode="mean_sqrt_len_tokens",batch_size=128,max_seq_length=512):

    one_stage_task_cfg = {
        "eval_backend": "RAGEval",
        "eval_config": {
            "tool": "MTEB",
            "model": [
                {
                    "model_name_or_path": model_name_or_path,
                    "pooling_mode": pooling_mode,
                    "max_seq_length": max_seq_length,
                    "prompt": prompt,
                    "model_kwargs": {"torch_dtype": "auto"},
                    "encode_kwargs": {
                        "batch_size": batch_size,
                    },
                }
            ],
            "eval": {
                "tasks": [
                    "T2Retrieval",
                    "MMarcoRetrieval",
                    "DuRetrieval",
                    "CovidRetrieval",
                    "CmedqaRetrieval",
                    "EcomRetrieval",
                    "MedicalRetrieval",
                    "VideoRetrieval"
                ],
                "verbosity": 2,
                "output_folder": "outputs",
                "overwrite_results": True,
                "limits":500000
            },
        },
    }

    # Run task
    run_task(task_cfg=one_stage_task_cfg)


if __name__ == "__main__":
    model_name_or_path = sys.argv[1]
    prompt = sys.argv[2]
    pooling_mode = sys.argv[3]
    batch_size = int(sys.argv[4])
    max_seq_length = int(sys.argv[5])
    run_eval(model_name_or_path, prompt, pooling_mode, batch_size, max_seq_length)
```

model_name_or_path = bge-large-zh
prompt = "为这个句子生成表示以用于检索相关文章："
pooling_mode = "cls"
batch_size = 512
max_seq_length = 512

**Comment by Yunnglin** [comment]
目前该问题已修复，原因是在embedding时给corpus错误添加了prompt，目前评测效果已与`CMTEB`对齐。
请拉取最新的代码并安装，评测`ndcg_at_10`时还请指定`top_k=10`，默认`top_k=5`，也会影响评测结果。
