### ISSUE TITLE
请问怎么设置指定输入输出的token长度，例如：支持1k 2k 4k 等，输出也是可以指定

### ISSUE THREAD

**Issue by Devliang24** [modelscope/evalscope#158]
请问怎么设置指定输入输出的token长度，例如：支持1k 2k 4k 等，输出也是可以指定

**Comment by Yunnglin** [comment]
- 设置`max_new_tokens` 参数可控制最大输出长度
  参考：https://evalscope.readthedocs.io/zh-cn/latest/get_started/basic_usage.html#id5
- 对于输入长度，token是数据集里给定的，这个得看数据集样本了，不支持指定

**Comment by Devliang24** [comment]
thx
