### ISSUE TITLE
输出日志显示字符乱码，预期显示中文字符

### ISSUE THREAD

**Issue by Devliang24** [modelscope/evalscope#162]
## 问题描述 / Issue Description

请简要描述您遇到的问题。 / Please briefly describe the issue you encountered.

## 使用的工具 / Tools Used
- [ ] Native / 原生框架
- [ ] Opencompass backend
- [ ] VLMEvalKit backend 
- [ ] RAGEval backend
- [x] Perf / 模型推理压测工具
- [ ] Arena  /竞技场模式

## 执行的代码或指令 / Code or Commands Executed

请提供您执行的主要代码或指令。 / Please provide the main code or commands you executed. 例如 / For example:

evalscope perf --url 'http://xx:host/v1/chat/completions' --parallel 10 --model 'Qwen2.5-72B-Instruct' --log-every-n-query 10 --read-timeout=120 -n 10 --max-prompt-length 128000 --api openai --query-template '{"model": "%m", "messages": []}' --dataset-path '/home/user/datasets/my_data.jsonl'

## 错误日志 / Error Log

请粘贴完整的错误日志或控制台输出。 / Please paste the full error log or console output. 例如 / For example:

![image](https://github.com/user-attachments/assets/f9b83f8a-24cb-44af-b708-62f53ce57220)

## 运行环境 / Runtime Environment

- 操作系统 / Operating System:
  - [] Windows
  - [x] macOS
  - [x] Ubuntu

- Python版本 / Python Version:
  - [ ] 3.11
  - [x] 3.10
  - [ ] 3.9

## 其他信息 / Additional Information

如果有其他相关信息，请在此处提供。 / If there is any other relevant information, please provide it here.

**Comment by Yunnglin** [comment]
输出看起来不是乱码，而是终端没有正确配置unicode编码，尝试设置：
``` bash
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

**Comment by Devliang24** [comment]
thx
