### ISSUE TITLE
若设置最大输出tokens，想要让模型每次请求输出tokens数都打满这个最大输出token的值，或者接近这个值，需要怎么设置嘛？

### ISSUE THREAD

**Issue by Devliang24** [modelscope/evalscope#167]
## 问题描述 / Issue Description

请简要描述您遇到的问题。 / Please briefly describe the issue you encountered.

## 使用的工具 / Tools Used
- [ ] Native / 原生框架
- [ ] Opencompass backend
- [ ] VLMEvalKit backend 
- [ ] RAGEval backend
- [ * ] Perf / 模型推理压测工具
- [ ] Arena  /竞技场模式

## 执行的代码或指令 / Code or Commands Executed

请提供您执行的主要代码或指令。 / Please provide the main code or commands you executed. 例如 / For example:

evalscope perf --url 'http://xxxx:xxx/v1/chat/completions' --parallel 10 --model 'Qwen2.5-72B-Instruct' --log-every-n-query 10 --read-timeout=120 -n 10 --max-prompt-length 128000 --api openai --query-template '{"model": "%m", "messages": []}' --dataset-path '/home/user/datasets/open_qa_1.jsonl' --wandb-api-key 'xxxxx' --name 'demo_9' --max-tokens 600  --stop-token-ids

## 运行环境 / Runtime Environment

- 操作系统 / Operating System:
  - [ ] Windows
  - [ ] macOS
  - [*] Ubuntu

- Python版本 / Python Version:
  - [ ] 3.11
  - [*] 3.10
  - [ ] 3.9

## 其他信息 / Additional Information

如果有其他相关信息，请在此处提供。 / If there is any other relevant information, please provide it here.

**Comment by Yunnglin** [comment]
这个需要自定义prompt让模型去输出长文本，例如加上限制“不少于2000字”等

**Comment by Devliang24** [comment]
thx

**Comment by Devliang24** [comment]
> 这个需要自定义prompt让模型去输出长文本，例如加上限制“不少于2000字”等

不能完全有效，比如 设置不少于 10000 字，实际还是会少于

**Comment by Yunnglin** [comment]
是可能会有这个问题，目前的模型一次性输出很长的文本都不太行，除非专门进行过长文本微调。您可以多尝试构造不同的prompt，或增大 temperature、top_k 和 top_p

**Comment by yingdachen** [comment]
> > 这个需要自定义prompt让模型去输出长文本，例如加上限制“不少于2000字”等
> 
> 不能完全有效，比如 设置不少于 10000 字，实际还是会少于

并不是所有的大模型都能具备输出长文本的能力。可以参考这几个工作：

https://arxiv.org/abs/2408.07055
https://arxiv.org/abs/2410.10210

**Comment by Devliang24** [comment]
> 是可能会有这个问题，目前的模型一次性输出很长的文本都不太行，除非专门进行过长文本微调。您可以多尝试构造不同的prompt，或增大 temperature、top_k 和 top_p

这个只能试下了

**Comment by yingdachen** [comment]
> > > > 这个需要自定义prompt让模型去输出长文本，例如加上限制“不少于2000字”等
> > > 
> > > 
> > > 不能完全有效，比如 设置不少于 10000 字，实际还是会少于
> > 
> > 
> > 并不是所有的大模型都能具备输出长文本的能力。可以参考这几个工作：
> > https://arxiv.org/abs/2408.07055 https://arxiv.org/abs/2410.10210
> 
> 我验证的模型是 Qwen2.5-72B-Instruct 模型，官方说支持输入输出tokens可以到32k的

支持up to 32K token的输出，并不是说对于任何输入，都能保证输出达到指定长度的。 另外调整prompt，调整不同参数等，都会有不同的结果。
