### ISSUE TITLE
测试的结果数据统计好像有问题，为什么 首token 平均时间和每个包平均时延 平均时延 是一样？

### ISSUE THREAD

**Issue by Devliang24** [modelscope/evalscope#168]
## 问题描述 / Issue Description

请简要描述您遇到的问题。 / Please briefly describe the issue you encountered.

## 使用的工具 / Tools Used
- [ ] Native / 原生框架
- [ ] Opencompass backend
- [ ] VLMEvalKit backend 
- [ ] RAGEval backend
- [*] Perf / 模型推理压测工具
- [ ] Arena  /竞技场模式

## 执行的代码或指令 / Code or Commands Executed

请提供您执行的主要代码或指令。 / Please provide the main code or commands you executed. 例如 / For example:

evalscope perf --url 'http://xxxxxxx/v1/chat/completions' --parallel 10 --model 'Qwen2.5-72B-Instruct' --log-every-n-query 10 --read-timeout=120 -n 10 --max-prompt-length 128000 --api openai --query-template '{"model": "%m", "messages": []}' --dataset-path '/home/user/datasets/open_qa.jsonl'

## 错误日志 / Error Log

请粘贴完整的错误日志或控制台输出。 / Please paste the full error log or console output. 例如 / For example:

![image](https://github.com/user-attachments/assets/e9c43a26-7ec9-4ec4-b70f-03820d3cdc2b)

## 运行环境 / Runtime Environment

- 操作系统 / Operating System:
  - [ ] Windows
  - [ ] macOS
  - [*] Ubuntu

- Python版本 / Python Version:
  - [ ] 3.11
  - [*] 3.10
  - [ ] 3.9

## 其他信息 / Additional Information

工具版本
![image](https://github.com/user-attachments/assets/4646f415-bc6b-4342-b9c3-996cb3a68746)

如果有其他相关信息，请在此处提供。 / If there is any other relevant information, please provide it here.

**Comment by Yunnglin** [comment]
参考 https://github.com/modelscope/evalscope/issues/141
