### ISSUE TITLE
Windows 11 下执行异常 

### ISSUE THREAD

**Issue by Devliang24** [modelscope/evalscope#169]
## 问题描述 / Issue Description

请简要描述您遇到的问题。 / Please briefly describe the issue you encountered.

## 使用的工具 / Tools Used
- [ ] Native / 原生框架
- [ ] Opencompass backend
- [ ] VLMEvalKit backend 
- [ ] RAGEval backend
- [*] Perf / 模型推理压测工具
- [ ] Arena  /竞技场模式

## 执行的代码或指令 / Code or Commands Executed

请提供您执行的主要代码或指令。 / Please provide the main code or commands you executed. 例如 / For example:

evalscope perf --url 'http://xxxxx/v1/chat/completions' --parallel 3 --headers 'Authorization=Bearer sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' --model 'Qwen2.5-72B-Instruct' --log-every-n-query 10 --read-timeout=120 -n 3 --max-prompt-length 128000 --api openai --query-template '{"model": "%m", "messages": []}' --dataset-path 'D:\api_demo\eval\datasets\1k\ddd.jsonl'

## 错误日志 / Error Log

请粘贴完整的错误日志或控制台输出。 / Please paste the full error log or console output. 例如 / For example:

![image](https://github.com/user-attachments/assets/5cebd073-cc9f-42a1-b61d-c52d1f82f6cd)

## 运行环境 / Runtime Environment

- 操作系统 / Operating System:
  - [*] Windows
  - [ ] macOS
  - [ ] Ubuntu

- Python版本 / Python Version:
  - [ ] 3.11
  - [*] 3.10
  - [ ] 3.9
  - [ ] 
![image](https://github.com/user-attachments/assets/594b2a2d-edc3-47ec-b917-8fab217edf72)
![image](https://github.com/user-attachments/assets/bc7f446a-2751-4d40-a37e-b12d218cb929)

## 其他信息 / Additional Information

如果有其他相关信息，请在此处提供。 / If there is any other relevant information, please provide it here.

**Comment by Yunnglin** [comment]
目前请尝试拉取`feat/perf`分支代码并安装使用
```bash
git clone https://github.com/modelscope/evalscope.git
cd evalscope
git fetch origin feat/perf
git checkout feat/perf
pip install -e .
```
此外，现在支持了`--api-key`参数，无需在headers部分输入
