### ISSUE TITLE
模型性能压测-evalscope perf-报错超时

### ISSUE THREAD

**Issue by NiYueLiuFeng** [modelscope/evalscope#177]
## 问题描述 / Issue Description

使用 evalscope perf进行模型模型压测超时，报错：2024-11-04 10:53:20,827 - perf - http_client.py - post - 171 - ERROR - Timeout on reading data from socket

## 使用的工具 / Tools Used
- [ ] Perf / 模型推理压测工具

## 执行的代码或指令 / Code or Commands Executed

```bash
evalscope  perf --url 'http://127.0.0.1:8080/v1/chat/completions' --parallel 1 --model 'InternVL2-26B' --log-every-n-query 10 --read-timeout=1200 --dataset-path './open_qa.jsonl' -n 1000 --max-prompt-length 128000 --api openai --dataset openqa
 
```

## 错误日志 / Error Log
使用vllm部署的模型，openai API接口。
后端可以看到接口被正常调用了。
![image](https://github.com/user-attachments/assets/2e02279d-7f89-4cdc-87be-19ae3060c3d9)

运行 evalscope  perf ....  报错如下：
2024-11-04 10:53:20,827 - perf - http_client.py - post - 171 - ERROR - Timeout on reading data from socket

## 运行环境 / Runtime Environment

- 操作系统 / Operating System:
  - [ ] Ubuntu

- Python版本 / Python Version:
  - [ ] 3.9

**Comment by Yunnglin** [comment]
我们修复一下这个问题

**Comment by Yunnglin** [comment]
目前请尝试拉取`feat/perf`分支代码并安装使用
```bash
git clone https://github.com/modelscope/evalscope.git
cd evalscope
git fetch origin feat/perf
git checkout feat/perf
pip install -e .
```
