### ISSUE TITLE
这些wandb指标数据可以获取到么

### ISSUE THREAD

**Issue by ouyongqi** [modelscope/evalscope#179]
## 问题描述 / Issue Description

![image](https://github.com/user-attachments/assets/f5f92bd7-195c-4da5-8f56-fe531a57920a)
这些图里面的指标数据可以获取到么。
![image](https://github.com/user-attachments/assets/6c67a561-be78-4353-94f7-4b6a402d6026)
跑完之后都是平均指标数据，没有图上的指标数据。

## 执行的代码或指令 / Code or Commands Executed
evalscope perf --url 'https://api.openai.com/v1/chat/completions' --parallel 4 --model 'qwen' --log-every-n-query 10 --read-timeout=120 -n 100 --max-prompt-length 128000 --api openai --query-template '{"model": "%m", "messages": [{"role": "user","content": "%p"}], "stream": false,"skip_special_tokens": false,"stop": ["<|im_end|>"]}' --dataset openqa --dataset-path '/workspace/data/eval.jsonl'

**Comment by Yunnglin** [comment]
请在启动时指定参数`--wandb-api-key 'your_wandb_api_key' --name 'name_of_wandb_and_result_db'`来使用wandb

**Comment by ouyongqi** [comment]
好像启动命令添加这两个参数要打通连接wandb的网络，而且这个是不是只能在wandb平台上才能看到数据。我可以不打通wandb网络，直接获取到这些图表数据么

**Comment by ouyongqi** [comment]
> 请在启动时指定参数`--wandb-api-key 'your_wandb_api_key' --name 'name_of_wandb_and_result_db'`来使用wandb

好像启动命令添加这两个参数要打通连接wandb的网络，而且这个是不是只能在wandb平台上才能看到数据。我可以不打通wandb网络，直接获取到这些图表数据么

**Comment by Yunnglin** [comment]
好像不行，除非自己私有化部署wandb

**Comment by ouyongqi** [comment]
> 好像不行，除非自己私有化部署wandb

好吧
