### ISSUE TITLE
我们evalscope支持多模态大模型的性能压测么

### ISSUE THREAD

**Issue by ouyongqi** [modelscope/evalscope#182]
## 问题描述 / Issue Description

我们evalscope是否支持多模态大模型的性能压测，可以输出类似下面指标：
![image](https://github.com/user-attachments/assets/f6953f7a-5139-43fd-9d6c-6fc184bfe635)

**Comment by Yunnglin** [comment]
目前不支持，正在重构这块代码，后续会加上的

**Comment by ouyongqi** [comment]
> 目前不支持，正在重构这块代码，后续会加上的

这个后续计划什么时候上线

**Comment by Yunnglin** [comment]
预计11月内完善这些功能

**Comment by ouyongqi** [comment]
> 预计11月内完善这些功能

ok

**Comment by Yunnglin** [comment]
目前已支持flickr8k这个图文数据集使用：

您可以拉取main分支代码，来使用最新的perf模块尝试，参考[使用指南](https://evalscope.readthedocs.io/zh-cn/latest/user_guides/stress_test/index.html)。

**Comment by Yunnglin** [comment]
由于长时间未收到活动，我们将关闭此问题。如果您有任何疑问，请随时重新打开它。如果EvalScope对您有所帮助，欢迎给我们点个STAR以示支持，谢谢！

**Comment by wangxingjun778** [comment]
补充，目前直接使用： pip install evalscope[perf] -U  即可， 目前版本： 0.7.0

详情参考：

1. QwQ-32B-Preview speed benchmark：
https://evalscope.readthedocs.io/zh-cn/latest/experiments/speed_benchmark/QwQ-32B-Preview.html

2. EvalScope GitHub: https://github.com/modelscope/evalscope

3. v0.7.0 Release note: https://github.com/modelscope/evalscope/releases/tag/v0.7.0

**Comment by divingwolf** [comment]
还有除 flickr8k 数据集以外的 其他数据集支持多模态大模型的性能压测吗

**Comment by divingwolf** [comment]
尽量提供更大的图片作为测试的数据集吧，不然每次输入token也就200多不到300，作为压力测试也太少了

**Comment by wangxingjun778** [comment]
> 尽量提供更大的图片作为测试的数据集吧，不然每次输入token也就200多不到300，作为压力测试也太少了

嗯，目前确实存在这个局限，我们近期再加一下更为复杂的benchmark

**Comment by divingwolf** [comment]
> > 尽量提供更大的图片作为测试的数据集吧，不然每次输入token也就200多不到300，作为压力测试也太少了
> 
> 嗯，目前确实存在这个局限，我们近期再加一下更为复杂的benchmark

感谢
