### ISSUE TITLE
evalscope 5.5 stream.日志不起作用

### ISSUE THREAD

**Issue by jinweida** [modelscope/evalscope#183]
evalscope perf --url 'http://127.0.0.1:9600/v1/chat/completions' \
--parallel 128 --model 'Qwen2___5-32B-Instruct' --log-every-n-query 10 --read-timeout=360 \
--dataset-path '/home/ai/.cache/evalscope/open_qa.jsonl' -n 2048 --max-prompt-length 128000 \
--tokenizer-path '/home/ai/hub/Qwen2___5-32B-Instruct' \
--api openai --stop '<|im_end|>' --stream --dataset openqa

使用者命令 
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/5d9d0856-7a6d-401b-9264-deb08ea9760e">
一致在输出流式的结果。5.2 是可以的

**Comment by Yunnglin** [comment]
目前在修改这部分逻辑，临时使用的话请注释掉下面一行：
https://github.com/modelscope/evalscope/blob/671e71bd214eba1c7e9fa1f90e0f0d4ff9ab04e5/evalscope/perf/http_client.py#L570
