### ISSUE TITLE
RAG测试样例中的测试集在什么地方下载，能否提供一下

### ISSUE THREAD

**Issue by charliedream1** [modelscope/evalscope#190]

**Comment by Yunnglin** [comment]
RAG测试样例在文档中有给出：参考 https://evalscope.readthedocs.io/zh-cn/latest/user_guides/backend/rageval_backend/ragas.html#id3

**Comment by charliedream1** [comment]
测试集在哪下载？只能自己造吗？



---原始邮件---
发件人: "Yunlin ***@***.***&gt;
发送时间: 2024年11月11日(周一) 下午2:38
收件人: ***@***.***&gt;;
抄送: "Optimus ***@***.******@***.***&gt;;
主题: Re: [modelscope/evalscope] RAG测试样例中的测试集在什么地方下载，能否提供一下 (Issue #190)




 
RAG测试样例在文档中有给出：参考 https://evalscope.readthedocs.io/zh-cn/latest/user_guides/backend/rageval_backend/ragas.html#id3

**Comment by Yunnglin** [comment]
是的，需要自己构造这个格式https://evalscope.readthedocs.io/zh-cn/latest/user_guides/backend/rageval_backend/ragas.html#id3 的数据集，因为这个评估的是RAG流程，需要对应流程生成的数据。

**Comment by charliedream1** [comment]
好



---原始邮件---
发件人: "Yunlin ***@***.***&gt;
发送时间: 2024年11月11日(周一) 下午5:16
收件人: ***@***.***&gt;;
抄送: "Optimus ***@***.******@***.***&gt;;
主题: Re: [modelscope/evalscope] RAG测试样例中的测试集在什么地方下载，能否提供一下 (Issue #190)




 
是的，需要自己构造这个格式https://evalscope.readthedocs.io/zh-cn/latest/user_guides/backend/rageval_backend/ragas.html#id3 的数据集，因为这个评估的是RAG流程，需要对应流程生成的数据。
