### ISSUE TITLE
generate-ragas: Aborted request  

### ISSUE THREAD

**Issue by jackqdldd** [modelscope/evalscope#194]
评测可以正常完成，生成用例的时候出现错误中止
![image](https://github.com/user-attachments/assets/d61a97c9-8401-42db-8263-d41d04774a04)
![image](https://github.com/user-attachments/assets/6dc319b8-98d7-4465-b9f2-826555630528)

是不是并发太多导致的？模型在L20上面2个GPU

**Comment by Yunnglin** [comment]
有可能，可能是模型端推理较慢，导致超时了

**Comment by jackqdldd** [comment]
好像没有可以设置并发的地方

**Comment by Yunnglin** [comment]
请尝试修改：
https://github.com/modelscope/evalscope/blob/fb2e0fd4d951adc0740b3683829ffcd34570540b/evalscope/backend/rag_eval/ragas/tasks/testset_generation.py#L200

**Comment by jackqdldd** [comment]
我拉取最新的代码然后安装，执行的时候报错：
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/evalscope/backend/rag_eval/__init__.py", line 1, in <module>
    from evalscope.backend.rag_eval.utils.embedding import EmbeddingModel
ModuleNotFoundError: No module named 'evalscope.backend.rag_eval.utils'

**Comment by Yunnglin** [comment]
是否使用`pip install -e .`安装，我这边没有复现

**Comment by jackqdldd** [comment]
上个问题解决了
`  runconfig = RunConfig(
        timeout=600, max_retries=1, max_wait=120, max_workers=1, log_tenacity=True
    )`
这样设置后执行的时候还是一次很多请求,另外请问文档分块的大小可以设置吗

**Comment by Yunnglin** [comment]
可以尝试修改如下代码，来修改load_data的逻辑：
https://github.com/modelscope/evalscope/blob/fb2e0fd4d951adc0740b3683829ffcd34570540b/evalscope/backend/rag_eval/ragas/tasks/testset_generation.py#L161

**Comment by jackqdldd** [comment]
![image](https://github.com/user-attachments/assets/6a502618-f75f-4251-bc96-5c8a2acac652)
提示词乱码

**Comment by Yunnglin** [comment]
这是在自动进行prompt翻译，其中有hindi语言的例子，并不是乱码

**Comment by jackqdldd** [comment]
ragas 最新0.2.4 不知道能不能解决这个问题

**Comment by Yunnglin** [comment]
我们看一下，会兼容新版本

**Comment by jackqdldd** [comment]
> 请尝试修改：
> 
> https://github.com/modelscope/evalscope/blob/fb2e0fd4d951adc0740b3683829ffcd34570540b/evalscope/backend/rag_eval/ragas/tasks/testset_generation.py#L200

我在这个路径下修改了，但是执行的时候还是默认的run_config：
`/home/alg/qdl/evalscope/package/evalscope/backend/rag_eval/ragas/tasks/testset_generation.py`

**Comment by jackqdldd** [comment]
![image](https://github.com/user-attachments/assets/7a2112c8-50b1-4ba5-a0a9-fa53a8a05830)

**Comment by jackqdldd** [comment]
重新安装后正常了

**Comment by jackqdldd** [comment]
apply_transforms 没有传runconfig ,导致并发太多
`evalscope/backend/rag_eval/ragas/tasks/testset_generation.py#get_knowledge_graph  `

**Comment by Yunnglin** [comment]
这个问题我们会在兼容ragas新版本时一并修复
