### ISSUE TITLE
bbh测试集之前可以测，现在测不了了

### ISSUE THREAD

**Issue by charliedream1** [modelscope/evalscope#202]
bbh测试集之前可以测，现在测不了了。会提示不在支持的测试集列表内

**Comment by wangxingjun778** [comment]
BBH前期有多个用户有report在使用中会出现import出错的问题（目前看是偶发，可能跟环境有关），在0.6.0版本做了临时移除，防止在以上环境block评测链路；  
可以使用如下版本： 
`pip install evalscope==0.6.0rc0` 来使用BBH  （跟0.6.0的唯一区别只有BBH）

偶发问题我们会尽快定位。

**Comment by charliedream1** [comment]
好
