### ISSUE TITLE
测试ragas时报错， nomodule named "evalscope.backend.rag_eval_utils'

### ISSUE THREAD

**Issue by goudemaoningsir** [modelscope/evalscope#203]
evalscope==0.6.0

测试ragas时报错， nomodule named "evalscope.backend.rag_eval_utils'

l另外，咨询一下 如何自定义模型及embedding模型

**Comment by Yunnglin** [comment]
目前请尝试使用源码安装：https://evalscope.readthedocs.io/zh-cn/latest/get_started/installation.html#id2

自定义模型及embedding模型参考：https://evalscope.readthedocs.io/zh-cn/latest/user_guides/backend/rageval_backend/ragas.html#id5

**Comment by chaoStart** [comment]
你需要安装最新的evalscope

**Comment by Yunnglin** [comment]
由于长时间未收到活动，我们将关闭此问题。如果您有任何疑问，请随时重新打开它。如果EvalScope对您有所帮助，欢迎给我们点个STAR以示支持，谢谢！
