### ISSUE TITLE
perf统计性能数据问题

### ISSUE THREAD

**Issue by weibingo** [modelscope/evalscope#204]
## 问题描述 / Issue Description

请简要描述您遇到的问题。 / Please briefly describe the issue you encountered.

## 使用的工具 / Tools Used
- [ ] Native / 原生框架
- [ ] Opencompass backend
- [ ] VLMEvalKit backend 
- [ ] RAGEval backend
- [√ ] Perf / 模型推理压测工具
- [ ] Arena  /竞技场模式

看了下代码，是根据流式最后一个data的usage来计算prompt_tokens和complete_tokens的，能否根据流式自己计算呢，有些服务流式不一定会返回usage。

**Comment by Yunnglin** [comment]
有两种方法：
1. 传`--tokenizer-path`将加载tokenizer计算usage
2. 可以自定义API，继承`OpenaiPlugin`，重写`parse_responses`函数

**Comment by hankexin00** [comment]
> 有两种方法：
> 
> 1. 传`--tokenizer-path`参数，我们将加载tokenizer来计算usage
> 2. 可以自定义API，继承`OpenaiPlugin`，重写`parse_responses`函数

传`--tokenizer-path`参数能够解决流式的问题，非流的似乎解决不了，无法获得perf统计的性能数据。

**Comment by weibingo** [comment]
> 有两种方法：
> 
> 1. 传`--tokenizer-path`参数，我们将加载tokenizer来计算usage
> 2. 可以自定义API，继承`OpenaiPlugin`，重写`parse_responses`函数

继承OpenaiPlugin就可以么，那执行参数需要变么？

**Comment by Yunnglin** [comment]
重写parse responses函数，传入参数不要变

**Comment by Yunnglin** [comment]
请参考[自定义API教程](https://evalscope.readthedocs.io/zh-cn/latest/user_guides/stress_test.html#api)

**Comment by Yunnglin** [comment]
> 由于长时间未收到活动，我们将关闭此问题。如果您有任何疑问，请随时重新打开它。如果EvalScope对您有所帮助，欢迎给我们点个STAR以示支持，谢谢！
