### ISSUE TITLE
并发请求感觉并不对

### ISSUE THREAD

**Issue by XYZliang** [modelscope/evalscope#213]
## 问题描述 / Issue Description

在华为国产服务器使用流式压测兼容 openai api 后端（这里使用的是 mindie），无论是使用在python代码还是命令使用，无论参数--rate还是--parallel还是全部使用，启用并发感觉没有完全并发。

代码详见下文。在启用流式，保持总数16的情况下，分别测试rate为8、parallel为8、rate和parallel为8的情况：

rate为8：请求花费106s

parallel为8：请求花费56s

rate和parallel为8：请求花费56s

自己写的并发请求代码（偷懒，没启动流式）：请求花费20s

rate和parallel为8但不启用流式：请求花费56s

## 使用的工具 / Tools Used

- [ ] Native / 原生框架
- [ ] Opencompass backend
- [ ] VLMEvalKit backend 
- [ ] RAGEval backend
- [x] Perf / 模型推理压测工具
- [ ] Arena  /竞技场模式

## 执行的代码或指令 / Code or Commands Executed

```python
#在保持下列command_line_args一样的情况下，分别测试了加入rate为8、parallel为8、rate和parallel为8的情况。
command_line_args = [
            "--url", "http://127.0.0.1:1025/v1/chat/completions",
            "-n", "16",
            "--model", "qwen",
            "--log-every-n-query", "10",
            "--read-timeout", "120",
            "--max-prompt-length", "8192",
            "--api", "openai",
            "--query-template",
            '{"model": "%m", "messages": [{"role": "user","content": "%p"}], "stream": true,"skip_special_tokens": false,"stop": ["<|im_end|>"]}',
            "--dataset", "openqa",
            "--tokenizer-path", "/mnt/data/model/Qwen/Qwen2-7B-Instruct/Qwen/Qwen2-7B-Instruct",
            "--max-tokens", "8192",
            "--stream",
            "--debug"
        ]
        task_cfg = command_line_args_to_dict(command_line_args)
        run_perf_benchmark(task_cfg)
```

## 运行环境 / Runtime Environment

- 操作系统 / Operating System:
  - [ ] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [x] 华为闭源欧拉

- Python版本 / Python Version:
  - [ ] 3.11
  - [x] 3.10
  - [ ] 3.9

## 其他信息 / Additional Information

版本为1128晚上从modelscope clone并pip install -e .的最新版

四个情况下的请求日志如下
[python_only_rate&para8_no_stream.log](https://github.com/user-attachments/files/17940422/python_only_rate.para8_no_stream.log)
[python_only_para8.log](https://github.com/user-attachments/files/17940423/python_only_para8.log)
[python_only_rate&para8.log](https://github.com/user-attachments/files/17940424/python_only_rate.para8.log)
[python_only_rate8.log](https://github.com/user-attachments/files/17940425/python_only_rate8.log)

**Comment by Yunnglin** [comment]
请问你自己写的并发请求是怎么实现的呢

**Comment by XYZliang** [comment]
> 请问你自己写的并发请求是怎么实现的呢

[参考这个链接](https://blog.csdn.net/arkohut/article/details/139076652)，在这个代码基础上改成读取openqa数据集，并发挨个取openqa数据集。

**Comment by Lorrrrraine** [comment]
我自己测试的时候感觉也是有点小问题，一是并非是完全并发，二是TTFT那里计算感觉不太对

**Comment by Yunnglin** [comment]
> 我自己测试的时候感觉也是有点小问题，一是并非是完全并发，二是TTFT那里计算感觉不太对

并发请求这里我再看一下；TTFT这里只有stream模型才生效

**Comment by Yunnglin** [comment]
对这块做了修复，麻烦拉取最新代码再尝试一下

**Comment by Yunnglin** [comment]
补充说明：在本工具的实现中请求生成与发送是分开的： --rate参数用于控制每秒生成的请求数量，请求将放入请求队列。 --parallel参数用于控制发送请求的worker数量，worker将从请求队列获取请求并发送，且在上一请求回复后才发送下一请求。 两个参数不建议同时设置，也即在本工具中，--rate参数仅对--parallel为1时有效。

**Comment by XYZliang** [comment]
辛苦，晚些时候会测试
