### ISSUE TITLE
evalscope 不存在 0.7.0 版本

### ISSUE THREAD

**Issue by shell-nlp** [modelscope/evalscope#218]
pip install evalscope 不存在 0.7.0 版本

**Comment by wangxingjun778** [comment]
> pip install evalscope 不存在 0.7.0 版本

已经发布到pypi了，参考： https://pypi.org/project/evalscope/#history

**Comment by wangxingjun778** [comment]
如果不是原生的pypi源，比如清华源、阿里云的源等，可能有一定延迟。
