### ISSUE TITLE
ragas eval error

### ISSUE THREAD

**Issue by BiaoZhouZz** [modelscope/evalscope#226]
我按照运行了Readme.md中ragas评估部分代码 :
eval_task_cfg = {
    "eval_backend": "RAGEval",
    "eval_config": {
        "tool": "RAGAS",
        "eval": {
            "testset_file": "/home/fr/evalscope/dataset/test_with_answer.json",
            "critic_llm": {
                "model_name_or_path": "/home/fr/ChatGLM/THUDM/Qwen2.5-7B-Instruct",
                "template_type": "qwen",
            },
            "embeddings": {
                "model_name_or_path": "/home/fr/ChatGLM/THUDM/bge-large-zh-1.5",
            },
            "metrics": [
                "faithfulness",
                "answer_relevancy",
                "context_precision",
                "answer_correctness",
            ],
        },
    },
}

# Run task
run_task(task_cfg=eval_task_cfg) # or run_task(task_cfg=generate_testset_task_cfg)

出现以下错误：
2024-12-02 16:56:36,160 - evalscope - INFO - Check `ragas` Installed
Traceback (most recent call last):
  File "/home/fr/evalscope/evalrag.py", line 111, in <module>
    run_task(task_cfg=eval_task_cfg) # or run_task(task_cfg=generate_testset_task_cfg)
  File "/home/fr/evalscope/evalscope/run.py", line 213, in run_task
    rag_eval_backend_manager.run()
  File "/home/fr/evalscope/evalscope/backend/rag_eval/backend_manager.py", line 75, in run
    self.run_ragas(testset_args, eval_args)
  File "/home/fr/evalscope/evalscope/backend/rag_eval/backend_manager.py", line 56, in run_ragas
    rag_eval(EvaluationArguments(**eval_args))
  File "/home/fr/evalscope/evalscope/backend/rag_eval/ragas/task_template.py", line 27, in rag_eval
    llm = LLM.load(**args.critic_llm)
  File "/home/fr/evalscope/evalscope/backend/rag_eval/utils/llm.py", line 21, in load
    return LocalLLM(**kw)
  File "/home/fr/evalscope/evalscope/backend/rag_eval/utils/llm.py", line 35, in __init__
    super().__init__(**kw)
  File "/home/fr/anaconda3/envs/ros2/envs/evalscope/lib/python3.10/site-packages/langchain_core/load/serializable.py", line 125, in __init__
    super().__init__(*args, **kwargs)
  File "/home/fr/anaconda3/envs/ros2/envs/evalscope/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 3 validation errors for LocalLLM
model_name
  Field required [type=missing, input_value={'model_name_or_path': '/...'template_type': 'qwen'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
model
  Field required [type=missing, input_value={'model_name_or_path': '/...'template_type': 'qwen'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
generation_config
  Field required [type=missing, input_value={'model_name_or_path': '/...'template_type': 'qwen'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing

**Comment by Yunnglin** [comment]
请问使用的ragas版本是多少

**Comment by BiaoZhouZz** [comment]
> 请问使用的evalscope和ragas版本是多少

evalscope版本是0.7.1，ragas版本是0.2.5

**Comment by Yunnglin** [comment]
我们复现一下

**Comment by Yunnglin** [comment]
用下面的配置评估，没有复现你说的问题，你参考一下
```python
eval_task_cfg = {
    "eval_backend": "RAGEval",
    "eval_config": {
        "tool": "RAGAS",
        "eval": {
            "testset_file": "outputs/testset_chinese_with_answer.json",
            "critic_llm": {
                "model_name_or_path": "qwen/Qwen2-7B-Instruct",
                "template_type": "qwen",
            },
            "embeddings": {
                "model_name_or_path": "AI-ModelScope/bge-large-zh",
            },
            "metrics": [
                "Faithfulness",
                "AnswerRelevancy",
                "ContextPrecision",
                "AnswerCorrectness",
            ],
            "language": "chinese",
        },
    },
}
```

**Comment by Yunnglin** [comment]
> 由于长时间未收到活动，我们将关闭此问题。如果您有任何疑问，请随时重新打开它。如果EvalScope对您有所帮助，欢迎给我们点个STAR以示支持，谢谢！
