### ISSUE TITLE
请问压测工具能不能添加tpot的p99，p95这些指标的监控

### ISSUE THREAD

**Issue by everloom** [modelscope/evalscope#235]
## 功能描述 / Feature Description

请简要描述您希望添加的功能。 / Please briefly describe the feature you would like to request.

## 需求背景 / Background

为什么需要这个功能？ / Why is this feature needed?

## 预期行为 / Expected Behavior

这个功能应该如何工作？ / How should this feature work?

## 其他信息 / Additional Information

还有其他相关信息吗？ / Any other relevant information?

**Comment by Yunnglin** [comment]
可以具体解释下tpot是什么指标吗，是如何计算的，方便我们添加这个功能

**Comment by yingdachen** [comment]
> 可以具体解释下tpot是什么指标吗，是如何计算的，方便我们添加这个功能

time per output token。另外p99/p95等选项，对于ttft（time to first token）等指标可以都一并加一下。

**Comment by everloom** [comment]
> 可以具体解释下tpot是什么指标吗，是如何计算的，方便我们添加这个功能

这几个里面解释了一下tpot（time per output token）的含义和计算方式
https://arxiv.org/html/2407.07000v1
https://learn.microsoft.com/en-us/azure/databricks/machine-learning/foundation-models/prov-throughput-run-benchmark

**Comment by Yunnglin** [comment]
我们会尽快加上这些指标

**Comment by everloom** [comment]
十分感谢
