### ISSUE TITLE
使用stream参数无法正常工作

### ISSUE THREAD

**Issue by DaiJianghai** [modelscope/evalscope#244]
## 问题描述 / Issue Description

使用perf压测llama3-8b-instruct，编写python脚本进行测试，出现400错误

## 使用的工具 / Tools Used
- [ ] Native / 原生框架
- [ ] Opencompass backend
- [ ] VLMEvalKit backend
- [ ] RAGEval backend
- [x] Perf / 模型推理压测工具
- [ ] Arena  /竞技场模式

## 执行的代码或指令 / Code or Commands Executed

```python
from evalscope.perf.main import run_perf_benchmark

framework = "vLLM"
model = "Meta-Llama-3-8B-Instruct"
dataset = "openqa"

task_cfg = {
            # base
            "url": "http://172.18.23.200:8009/v1/chat/completions",
            "api": "openai",
            "model": "Meta-Llama-3-8B-Instruct",
            
            # request control
            "number": 1000,
            "parallel": 100,
            "stream": True,

            # dataset
            "dataset": "openqa",
            "dataset_path": r"D:\JianghaiDai\project\experimental\evalscope\dataset\open_qa_5261.jsonl",
            
            # output
            "outputs_dir": r"D:\JianghaiDai\project\experimental\evalscope\results",
            
            # wandb
            # "wandb_api_key": "102368cbef58520a1ae7200b9c6c7b981096aab0",
            # "name": f"{framework}-{model}-{dataset}"
        }
run_perf_benchmark(task_cfg)
```

## 错误日志 / Error Log

```
2024-12-16 16:56:12,715 - evalscope - ERROR - Request: {'messages': [{'role': 'user', 'content': 'What is a jet engine?'}], 'model': 'Meta-Llama-3-8B-Instruct', 'max_tokens': 2048, 'seed': 42, 'stop': [], 'stream': True, 'stream_options': {'include_usage': True}, 'stop_token_ids': []} failed, state_code: 400, data: {"object": "error", "message": "[{'type': 'extra_forbidden', 'loc': ('body', 'stream_options'), 'msg': 'Extra inputs are not permitted', 'input': {'include_usage': True}}]", "type": "BadRequestError", "param": null, "code": 400}

请求全部失败
```

## 运行环境 / Runtime Environment

- 操作系统 / Operating System:
  - [ ] Windows
  - [ ] macOS
  - [x] Ubuntu

- Python版本 / Python Version:
  - [ ] 3.11
  - [x ] 3.10
  - [ ] 3.9

## 其他信息 / Additional Information

D:\JianghaiDai\project\experimental\evalscope\dataset\open_qa_5261.jsonl中的文件格式如下：
{"question":"Why can camels survive for long without water?","response":"Camels use the fat in their humps to keep them filled with energy and hydration for long periods of time."}
{"question":"Alice's parents have three daughters: Amy, Jessy, and what’s the name of the third daughter?","response":"The name of the third daughter is Alice"}

当设置stream为False的时候没有问题，但由于我要区分首个token返回时间和响应完成latency，故而修改stream为True

**Comment by Yunnglin** [comment]
请问使用的模型推理服务是什么，有启动命令吗

**Comment by Yunnglin** [comment]
> 感谢你的反馈！我们将关闭此问题。如果您有任何疑问，请随时重新打开它。如果EvalScope对您有所帮助，欢迎给我们点个STAR以示支持，谢谢！

**Comment by ShaohonChen** [comment]
你好，我在做性能测试时使用vllm作为后端还是遇到了相同的问题。

使用vllm版本：0.6.3.post1

vllm启动命令：`vllm serve /data/nvme1/weights/Qwen2.5-0.5B-Instruct/ --enforce-eager`

evalscope启动命令：`evalscope perf     --url "http://0.0.0.0:8000/v1/chat/completions" --model /data/nvme1/weights/Qwen2.5-0.5B-Instruct/ --api openai    --parallel 1     --number 5     --dataset openqa`

遇到错误信息：

```text
2025-04-06 17:50:55,603 - evalscope - ERROR - Request: {'messages': [{'role': 'user', 'content': '神州行手机号码成为空号了怎么办，卡里还有几十圆钱，还可以再用吗'}], 'model': '/data/nvme1/weights/Qwen2.5-0.5B-Instruct/', 'max_completion_tokens': 2048, 'seed': 42, 'stop': [], 'stop_token_ids': [], 'temperature': 0.0} failed, state_code: 400, data: {"object": "error", "message": "[{'type': 'extra_forbidden', 'loc': ('body', 'max_completion_tokens'), 'msg': 'Extra inputs are not permitted', 'input': 2048}]", "type": "BadRequestError", "param": null, "code": 400}
```

**Comment by ShaohonChen** [comment]
> 你好，我在做性能测试时使用vllm作为后端还是遇到了相同的问题。请问是不是我的vllm启动命令有问题呢？🤔
> 
> 使用vllm版本：0.6.3.post1
> 
> vllm启动命令：`vllm serve /data/nvme1/weights/Qwen2.5-0.5B-Instruct/ --enforce-eager`
> 
> evalscope启动命令：`evalscope perf --url "http://0.0.0.0:8000/v1/chat/completions" --model /data/nvme1/weights/Qwen2.5-0.5B-Instruct/ --api openai --parallel 1 --number 5 --dataset openqa`
> 
> 遇到错误信息：
> 
> ```
> 2025-04-06 17:50:55,603 - evalscope - ERROR - Request: {'messages': [{'role': 'user', 'content': '神州行手机号码成为空号了怎么办，卡里还有几十圆钱，还可以再用吗'}], 'model': '/data/nvme1/weights/Qwen2.5-0.5B-Instruct/', 'max_completion_tokens': 2048, 'seed': 42, 'stop': [], 'stop_token_ids': [], 'temperature': 0.0} failed, state_code: 400, data: {"object": "error", "message": "[{'type': 'extra_forbidden', 'loc': ('body', 'max_completion_tokens'), 'msg': 'Extra inputs are not permitted', 'input': 2048}]", "type": "BadRequestError", "param": null, "code": 400}
> ```

我测试了下，似乎使用新版本的vllm（0.8.1）不会出现错误，而使用安装evalscope自带的vllm时会报错T_T
