### ISSUE TITLE
 cannot import name 'EvalBackend' from 'evalscope.utils' 

### ISSUE THREAD

**Issue by maoulee** [modelscope/evalscope#247]
## 问题描述 / Issue Description

请简要描述您遇到的问题。 / Please briefly describe the issue you encountered.
 cannot import name 'EvalBackend' from 'evalscope.utils' 
## 使用的工具 / Tools Used
- [x] Native / 原生框架
- [ ] Opencompass backend
- [ ] VLMEvalKit backend
- [ ] RAGEval backend
- [ ] Perf / 模型推理压测工具
- [ ] Arena  /竞技场模式

## 执行的代码或指令 / Code or Commands Executed
CUDA_VISIBLE_DEVCIES=0 swift eval \
  --model_type llama3-8B-Instruct \
  --model_id_or_path/root/.cache/modelscope/hub/LLM-Research/Meta-Llama-3-8B-Instruct/ \
  --eval_dataset general_qa \
  --infer_backend vllm \ # 可选项 [pt, vllm, lmdeploy]
  --eval_backend Native

## 错误日志 / Error Log
File "/root/miniconda3/lib/python3.10/site-packages/swift/cli/eval.py", line 2, in <module>
    from swift.llm import eval_main
  File "/root/miniconda3/lib/python3.10/site-packages/swift/utils/import_utils.py", line 54, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/root/miniconda3/lib/python3.10/site-packages/swift/utils/import_utils.py", line 63, in _get_module
    return importlib.import_module('.' + module_name, self.__name__)
  File "/root/miniconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/root/miniconda3/lib/python3.10/site-packages/swift/llm/eval.py", line 18, in <module>
    from evalscope.utils import EvalBackend
ImportError: cannot import name 'EvalBackend' from 'evalscope.utils' (/root/miniconda3/lib/python3.10/site-packages/evalscope/utils/__init__.py)

## 运行环境 / Runtime Environment

- 操作系统 / Operating System:
  - [ ] Windows
  - [ ] macOS
  - [* ] Ubuntu

- Python版本 / Python Version:
  - [ ] 3.11
  - [*] 3.10
  - [ ] 3.9

## 其他信息 / Additional Information
evalscope-0.8.0
ms-opencompass                    0.1.5
ms-swift                          2.6.1
ms-vlmeval                        0.0.12
modelscope                        1.21.0

如果有其他相关信息，请在此处提供。 / If there is any other relevant information, please provide it here.

**Comment by Yunnglin** [comment]
请使用安装evalscope 0.7.1版本尝试运行

**Comment by Yunnglin** [comment]
evalscope v0.8.1 已发布，修复了该问题，使用`pip install evalscope -U`来使用

**Comment by Yunnglin** [comment]
> 由于长时间未收到活动，我们将关闭此问题。如果您有任何疑问，请随时重新打开它。如果EvalScope对您有所帮助，欢迎给我们点个STAR以示支持，谢谢！
