### ISSUE TITLE
请问一下评估reranker模型为什么打分这么低，甚至还有的是0

### ISSUE THREAD

**Issue by ZHAOFEGNSHUN** [modelscope/evalscope#257]
<img width="1784" alt="截屏2024-12-19 17 10 35" src="https://github.com/user-attachments/assets/ef98a9cb-3ac5-4c10-97ef-6fd08cf1b57f" />
reranker模型应该怎样评估质量呢？怎样建立benchmark？

**Comment by Yunnglin** [comment]
麻烦贴下你执行的命令

评估reranker需要两阶段评测 [参考](https://evalscope.readthedocs.io/zh-cn/latest/user_guides/backend/rageval_backend/mteb.html#id6)

**Comment by ZHAOFEGNSHUN** [comment]
one_stage_task_cfg = {  # noqa
        'eval_backend': 'RAGEval',
        'eval_config': {
            'tool': 'MTEB',
            'model': [
                {
                    'model_name_or_path': '/home/xiezizhe/.jupyter/bge/bge-reranker-v2-m3',
                    'pooling_mode': 'cls',  # if not set, load from model config; use `cls` for bge series model
                    'max_seq_length': 512,
                    'prompt': '为这个句子生成表示以用于检索相关文章：',
                    'encode_kwargs': {
                        'batch_size': 512,
                    },
                }
            ],
            'eval': {
                'tasks': [
                    'TNews',
                    'CLSClusteringS2S',
                    'T2Reranking',
                    'ATEC',
                    'T2Retrieval',
                    'MMarcoRetrieval',
                    'DuRetrieval',
                    'CovidRetrieval',
                    'CmedqaRetrieval',
                    'EcomRetrieval',
                    'MedicalRetrieval',
                    'VideoRetrieval'
                ],
                'verbosity': 2,
                'output_folder': 'outputs',
                'overwrite_results': True,
                'top_k': 10,
                'limits': 1000,  # don't limit for retrieval task
            },
        },
    }
    原来需要两阶段测评嘛？
    还有一个问题就是，现在reranker模型就只有那几个，用embedding模型来做rerank是可行的吗？

**Comment by ZHAOFEGNSHUN** [comment]
> 麻烦贴下你执行的命令
> 
> 评估reranker需要两阶段评测 [参考](https://evalscope.readthedocs.io/zh-cn/latest/user_guides/backend/rageval_backend/mteb.html#id6)

根据上面的one_stage_task_cfg 直接执行example_eval_mteb.py文件，CUDA_VISIBLE_DEVICES=6 python example_eval_mteb.py

**Comment by Yunnglin** [comment]
直接用embedding模型的话 [参考](https://evalscope.readthedocs.io/zh-cn/latest/user_guides/backend/rageval_backend/mteb.html#id5)；评测reranker需要用retrieval数据集，先用embedding模型检索topk，再进行排序

**Comment by ZHAOFEGNSHUN** [comment]
> 直接用embedding模型的话 [参考](https://evalscope.readthedocs.io/zh-cn/latest/user_guides/backend/rageval_backend/mteb.html#id5)；评测reranker需要用retrieval数据集，先用embedding模型检索topk，再进行排序

还有一个问题就是，现在reranker模型就只有那几个，如果说用embedding模型来做rerank是可行的吗？

**Comment by Yunnglin** [comment]
> 还有一个问题就是，现在reranker模型就只有那几个，如果说用embedding模型来做rerank是可行的吗？

可以用embedding模型来做rerank，但效果可能不如专门训练过的reranker

**Comment by ZHAOFEGNSHUN** [comment]
<img width="1147" alt="截屏2024-12-19 18 31 49" src="https://github.com/user-attachments/assets/21c71bdd-fda6-4df8-a58e-4620d5c2731d" />
您好，还想请教一下二阶段评估reranker我用的bge-reranker-v2-m3，得出的指标如上图，带有nauc前缀的指标较高，没带的就很低，实际我们在使用的时候主要看重哪些指标来评估这个reranker模型效果好不好呀？
