### ISSUE TITLE
微调模型评测&自建评测数据集

### ISSUE THREAD

**Issue by HaltonJiang** [modelscope/evalscope#48]
1、请问针对lora微调之后但没有合并的大模型，如何加载checkpoint进行评测呢？
2、支持自定义评测数据集进行评测吗？如何操作呢？或对格式有什么要求吗？

**Comment by Yunnglin** [comment]
1. 微调后的模型可以使用 ms-swift 集成的eval能力进行评测，指定 `--ckpt_dir` 参数
  参考： https://evalscope.readthedocs.io/zh-cn/latest/best_practice/swift_integration.html#id3

2. 自定义评测数据集教程参考：https://evalscope.readthedocs.io/zh-cn/latest/advanced_guides/custom_dataset.html

**Comment by 128veg80** [comment]
> 1、请问针对lora微调之后但没有合并的大模型，如何加载checkpoint进行评测呢？ 2、支持自定义评测数据集进行评测吗？如何操作呢？或对格式有什么要求吗？

同学你搞定了吗
