### ISSUE TITLE
运行run.py出错，说没有eval_config

### ISSUE THREAD

**Issue by aoligei178** [modelscope/evalscope#67]
python llmuses/run.py 
--model /media/ama/data1/wzh/Model_Param/LLM/Yi_6B/pretrain
 --template-type chatglm3 
--datasets arc 
--dataset-hub Local 
--dataset-dir /home/wzh/DianWang/RAG_project/Data/LLM/qa1000.json 
--limit 10
我想用自己的数据集测试本地模型，配置这些参数后报错如下：
 assert eval_config is not None, 'Please provide eval_config for specific evaluation backend.'
AssertionError: Please provide eval_config for specific evaluation backend.
找不到eval_config，请问这个从哪找

**Comment by aoligei178** [comment]
有没有大佬帮帮我

**Comment by Noyiz** [comment]
把run.py的382、383行注释掉
![Uploading 屏幕截图 2024-07-04 163706.png…]()

**Comment by Noyiz** [comment]
把run.py的382、383行注释掉
<img width="432" alt="屏幕截图 2024-07-04 163706" src="https://github.com/modelscope/eval-scope/assets/104254868/28b52a39-5a9a-416a-b136-124005cb869e">

**Comment by wangxingjun778** [comment]
Fixed, pull main branch and try again.
