### ISSUE TITLE
配置eval scope环境时报错：FileNotFoundError: [Errno 2] No such file or directory: './MANIFEST.in'

### ISSUE THREAD

**Issue by Juvember** [modelscope/evalscope#72]
按照readme中的指引配置环境时，运行“pip install -e .”命令后报错：FileNotFoundError: [Errno 2] No such file or directory: './MANIFEST.in'，这个怎么解决呢
![image](https://github.com/modelscope/eval-scope/assets/169908719/623c7470-f661-44a7-affa-26fbc1ab25fa)

**Comment by wangxingjun778** [comment]
Please pull latest main branch.
