### ISSUE TITLE
OpenCompass 支持设置请求的参数模板吗，类似perf模块的--query-template  

### ISSUE THREAD

**Issue by jackqdldd** [modelscope/evalscope#81]
待测模型是基于Qwen2-72B-Instruct-AWQ的一个服务，请求示例：
`{
"model": "Qwen2-72B-Instruct-AWQ-RAG",
"messages": [
{"role": "user", "content": "请给我讲个冷笑话"}
],
"temperature": 0.1
}`

想测试下needlebench_4k 数据集，请求的参数格式和示例的不一致导致结果不对

**Comment by slin000111** [comment]
examples/tasks/default_eval_swift_openai_api.json
