### ISSUE TITLE
infor_vqa，doc_vqa数据集在计算指标时出现没有answer的情况

### ISSUE THREAD

**Issue by stay-leave** [modelscope/evalscope#92]
![截屏2024-08-06 18 37 27](https://github.com/user-attachments/assets/e9e87a37-da47-438b-be97-3f64433067eb)

示例中的chartqa是可以的，但是上面这俩不行

**Comment by Yunnglin** [comment]
评测模型是哪个呢，没有answer是模型没有prediction吗，还是说有prediction无法计算指标

**Comment by Yunnglin** [comment]
使用 InfoVQA_VAL，DocVQA_VAL 数据集评测，不要使用 InfoVQA_TEST，DocVQA_TEST 这两个test集没有提供 answer
