### ISSUE TITLE
eval_swift_openai是否支持并发测试，怎么配置？

### ISSUE THREAD

**Issue by charliedream1** [modelscope/evalscope#95]
eval_swift_openai是否支持并发测试，怎么配置？

**Comment by wangxingjun778** [comment]
可参考： https://github.com/modelscope/evalscope/blob/main/examples/example_eval_swift_openai_api.py

其中的eval_config中的`batch_size`字段，默认为8，可自行配置。

**Comment by charliedream1** [comment]
谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月14日(周三) 凌晨0:45
收件人: ***@***.***&gt;;
抄送: "Optimus ***@***.******@***.***&gt;;
主题: Re: [modelscope/evalscope] eval_swift_openai是否支持并发测试，怎么配置？ (Issue #95)




 
可参考： https://github.com/modelscope/evalscope/blob/main/examples/example_eval_swift_openai_api.py
 
其中的eval_config中的batch_size字段，默认为8，可自行配置。

**Comment by charliedream1** [comment]
想问一下这个测评全都是在本地测吗？会把结果发送到网上去做评估吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月14日(周三) 凌晨0:45
收件人: ***@***.***&gt;;
抄送: "Optimus ***@***.******@***.***&gt;;
主题: Re: [modelscope/evalscope] eval_swift_openai是否支持并发测试，怎么配置？ (Issue #95)




 
可参考： https://github.com/modelscope/evalscope/blob/main/examples/example_eval_swift_openai_api.py
 
其中的eval_config中的batch_size字段，默认为8，可自行配置。

**Comment by wangxingjun778** [comment]
均是在本地测试的

**Comment by charliedream1** [comment]
好，谢啦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月19日(周一) 中午1:53
收件人: ***@***.***&gt;;
抄送: "Optimus ***@***.******@***.***&gt;;
主题: Re: [modelscope/evalscope] eval_swift_openai是否支持并发测试，怎么配置？ (Issue #95)




 
均是在本地测试的

**Comment by Yunnglin** [comment]
由于长时间未收到活动，我们将关闭此问题。如果您有任何疑问，请随时重新打开它。如果EvalScope对您有所帮助，欢迎给我们点个STAR以示支持，谢谢！
