### ISSUE TITLE
请问VLM的自定义评测集怎么做？

### ISSUE THREAD

**Issue by stay-leave** [modelscope/evalscope#97]
大佬您好！没找到关于这个的教程，可以指点下吗？
我的想法是先用swift的infer，然后自己写指标计算代码，不知道这个项目有没有便捷方式

**Comment by Yunnglin** [comment]
VLM自定义评测集目前还没支持，后续会加上的

**Comment by Yunnglin** [comment]
文档已更新，请参考 https://evalscope.readthedocs.io/zh-cn/latest/advanced_guides/custom_dataset.html
