### ISSUE TITLE
OpenCompass，VLMEvalKit 评测模型的时候如何指定请求参数？

### ISSUE THREAD

**Issue by jackqdldd** [modelscope/evalscope#98]
本地部署的模型参数和默认的参数不一致，如何在调用的时候指定参数

**Comment by Yunnglin** [comment]
具体是什么参数不一致？
如果是模型推理的话，支持 temperature 参数

**Comment by jackqdldd** [comment]
模型服务地址：http://xxx.com.cn:9316/multimodal/glm4v
参数：{
  "query": "xxx",
  "image_path": "/data/ee_22_1714340162.jpeg",
 "history": []
}
![image](https://github.com/user-attachments/assets/a8a115fe-410e-4cd6-8605-16a662782690)

接口可以curl通，但是执行example_eval_vlm_swift.py 的时候一直卡着
![image](https://github.com/user-attachments/assets/bf60ae1e-4153-42bb-8fe2-0d0ee62911fe)

**Comment by Yunnglin** [comment]
目前只支持OpenAI API接口格式的调用
